Build badge and avatar page and components
ishitakeshawani/Feliz-UI pull request #1
Opened 2022-02-04 12:43 UTC by ishitakeshawani

2022-02-04 17:34 UTC, akshay-rajput requested changes
make these changes and ask for review later

2022-02-04 17:34 UTC, akshay-rajput commented on Components/Avatar/avatar.css
> +* {
if it's for a component, it should be in a class.
If it's general, it should be in a general css file

2022-02-04 17:34 UTC, akshay-rajput commented on Components/Avatar/avatar.css
> +  height: 5rem;
remove height, width from general avatar class as it is included in avatar-md class

2022-02-04 17:34 UTC, akshay-rajput commented on Components/Avatar/avatar.css
> +.sm {
change variant names to avatar-sm, etc.

2022-02-04 17:34 UTC, akshay-rajput commented on Components/Avatar/avatar.css
> +.square {
change class name to br-5 or something similar to indicate border radius

2022-02-04 17:34 UTC, akshay-rajput commented on index.html
> -        <a href="#" class="no-style doc-btn">Documentation</a>
change name to "link-no-style"

2022-02-04 17:34 UTC, akshay-rajput commented on pages/avatarpage.html
> +          <div class="item1">
follow similar naming convention i.e "item1" and other classes have dash in them. so follow same convention  everywhere.

2022-02-04 17:34 UTC, akshay-rajput commented on styles/avatarpage.css
> +.sm {
use these classes from avatar.css

2022-02-04 17:34 UTC, akshay-rajput commented on styles/drawer.css
> +.item1 {
add proper name

2022-02-05 16:47 UTC, ishitakeshawani commented
> make these changes and ask for review later

Can you re-review it now?
@akshay-rajput

2022-02-05 16:56 UTC, Creator-singh approved these changes
looks good to me.

2022-02-05 17:00 UTC, anupkgurung approved these changes
You have used PX it will give you issues when screen size changes. Preferred units would be rem ,%. And also consistent with units will help in the longer run.

2022-02-05 17:00 UTC, anupkgurung commented on styles/badge.css
> +
instead of importing all css into multiple css file you can import all in one and than use that one in html.

2022-02-05 17:00 UTC, anupkgurung commented on styles/page.css
> +  font-weight: 400;
i see you have used font-weight multiple times so what you could do is to move common used properties and add it to utility.

2022-02-05 17:17 UTC, ishitakeshawani commented on styles/badge.css
> +
done

2022-02-05 17:53 UTC, ishitakeshawani commented on styles/page.css
> +  font-weight: 400;
yes, I tried it. Thanks for recomending it.

2022-02-05 17:53 UTC, merged